# common.mk — the make interface every one of these repositories answers to.
#
# GENERATED by `litmo mk`. Edit litmo and run `make mk-update`; edits made
# here are overwritten and, worse, make three repositories disagree again.
#
# Nine verbs, the same everywhere, whatever is underneath them:
#
#   make            sync + render — the "I just cloned this" path
#   make env        install from the lockfile
#   make sync       pull data/ and out/ from object storage
#   make build      run the pipeline: data/ -> out/
#   make render     reports/*.qmd -> the formats this repo publishes
#   make preview    live preview of one report
#   make check      tests and validators
#   make publish    push data/ and out/ to object storage (maintainer only)
#   make reproduce  the whole thing, from an empty checkout
#   make clean      remove derived files
#
# The one rule underneath them all: **all the computing happens in the analysis
# modules, and no document does arithmetic.** That is what lets `freeze: false`
# be the setting everywhere — a rendered report has no cache to quote from, so
# it cannot be carrying a stale number.
#
# How a document reaches a number is the repository's own choice, and they
# differ: some read the artifacts in out/, others call the modules and format
# what comes back. The second recomputes from the inputs on every render, which
# is the stronger of the two — there is no stored artifact for a stale number
# to live in. This file does not assume either one.
#
# A repository's own Makefile sets a few variables, includes this, and defines
# `build` and `check`. Everything else is here.

UV     := uv run
LITMO := $(UV) litmo
Q      := $(UV) quarto

# Output formats for `make render`. gfm keeps a report readable and diffable
# in the repo; html is the one you send someone.
FORMATS ?= html

# Which report `make preview` and `make render-one` act on. The first one in
# reports/ unless you say otherwise: `make preview DOC=reports/OTHER.qmd`.
DOC ?= $(firstword $(wildcard reports/*.qmd))

# What `make reproduce` runs. A repo with expensive fetch stages lists them
# here, in order, instead of hiding them inside `build`.
REPRODUCE ?= env build render

# Extra paths for `make clean`, beyond the derived documents and scratch.
# Spliced into an `rm -rf`, so `clean` refuses anything absolute or containing
# `..` — repo-relative paths only.
CLEAN_EXTRA ?=

.DEFAULT_GOAL := default
.PHONY: default env sync status build render render-one preview check \
        publish reproduce clean clean-out mk-update doctor help

# `default: sync render` names two prerequisites, and prerequisites are not an
# order: `make -j2` starts the render while the pull is still moving files
# into out/, and the report that comes out is built from whatever had landed
# by then — successfully, with nothing to say it happened. A sub-make per
# stage is the portable way to write "then": the recipe lines run one after
# another whatever -j says, while `$(MAKE)` hands the jobserver down so each
# stage still parallelises inside itself. `.NOTPARALLEL` is the shorter
# spelling and the wrong one — it only takes prerequisites from GNU make 4.4,
# and every make before that (including the 3.81 Apple ships) ignores them
# and serialises the whole file instead.
default:  ## sync, then render — what a fresh clone runs
	@$(MAKE) --no-print-directory sync
	@$(MAKE) --no-print-directory render

## ---- environment --------------------------------------------------------
# `uv sync` installs from the committed lockfile, so a second machine
# reproduces this one rather than approximating it. Rendering additionally
# needs the `quarto` binary on PATH; `make doctor` says so if it is missing.

env:  ## install the locked environment
	uv sync

doctor:  ## check the toolchain, the config and the credentials
	@$(LITMO) doctor

## ---- data ---------------------------------------------------------------
# What moves, and whether it needs credentials, is declared in sync.toml.
# Where the bucket is public, `sync` needs no account anywhere.

sync:  ## pull data/ and out/ from object storage
	$(LITMO) pull

# `litmo status` exits non-zero when the two differ, which is what you want in
# a script. Here it is a thing a person reads, so the difference is reported
# rather than raised — make's "Error 1" would say less than the table already
# does. Gate on `uv run litmo status` directly if you need the exit code.
status:  ## compare this checkout against the bucket, move nothing
	@$(LITMO) status || echo "  differences above — 'make sync' pulls, 'make publish' pushes"

publish:  ## push data/ and out/ to object storage (maintainer only)
	$(LITMO) push

## ---- the documents ------------------------------------------------------
# Every output is named after its source, and LITMO_FORMAT tells document code
# which format it is being rendered into — the one hook a report needs to build
# a plain pipe table for markdown and a typeset one for HTML.

render: $(addprefix render-,$(FORMATS))  ## render every report, every format

render-%:
	LITMO_FORMAT=$* $(Q) render --to $*

render-one: $(addprefix render-one-,$(FORMATS))  ## render just $(DOC)

render-one-%:
	LITMO_FORMAT=$* $(Q) render $(DOC) --to $*

preview:  ## live preview of $(DOC)
	LITMO_FORMAT=html $(Q) preview $(DOC) --to html

## ---- everything ---------------------------------------------------------

# In order, and one at a time, for the same reason as `default` above: the
# stages a repo lists here are a pipeline, and `-j` would otherwise run the
# render against half-built inputs.
reproduce:  ## the whole thing, from an empty checkout
	@for stage in $(REPRODUCE); do \
	   $(MAKE) --no-print-directory $$stage || exit $$?; \
	 done

## ---- tidying ------------------------------------------------------------
# `clean` only removes what a render produces. Artifacts under out/ can be
# hours of computation and the bucket may be their only other copy, so
# `clean-out` is deliberately harder to run than typing four letters.

clean:  ## remove rendered documents and scratch
	@for p in $(CLEAN_EXTRA); do \
	   case "$$p" in /*|*..*) \
	     echo "CLEAN_EXTRA must be repo-relative: $$p" >&2; exit 1;; esac; \
	 done
	rm -rf .quarto _freeze reports/*_files reports/*.html $(CLEAN_EXTRA)
	find . -name __pycache__ -prune -exec rm -rf {} + 2>/dev/null || true

clean-out:  ## delete out/ — needs FORCE=1, and `make sync` to undo
ifndef FORCE
	@echo "out/ can be hours of computation, and the bucket may be its only"
	@echo "other copy. Check with \`make status\` first, then:"
	@echo "    make clean-out FORCE=1"
	@exit 1
endif
	rm -rf out

## ---- this file ----------------------------------------------------------

# Via a sibling, because `> common.mk` truncates the file before litmo runs:
# a missing package or a bad install then left a 0-byte common.mk, which
# `include` loads perfectly happily, and every target in this file was gone.
mk-update:  ## refresh common.mk from the installed litmo
	@$(LITMO) mk > common.mk.new || { rm -f common.mk.new; exit 1; }
	@mv -f common.mk.new common.mk
	@echo "common.mk refreshed — commit it"

help:  ## list the targets
	@awk 'BEGIN {FS = ":.*##"} \
	     /^[a-zA-Z][a-zA-Z0-9_-]*:.*##/ {printf "  %-14s %s\n", $$1, $$2}' \
	     $(MAKEFILE_LIST) | sort -u
